### ISSUE TITLE
Reorganize code for clarity 

### ISSUE THREAD

**Issue by debjyoti385** [InitialDLab/AIPro#10]
I am proposing that we make the file structure of the code as follows:

aipro
-    |- docs/                            Wiki and other documentation
-    |- web/                             Webserver and UI components
-    |- server/    or src/           AIPro backend code resides here  
--          |- model.py
--          |- main.py
--          |- api.py
--          |- data_sources/
--          |- ........
--          |- ........
-    |- install.sh                                Installation and running files. 
-    |- README.md
-    |- requirements.txt
-    |- docker-compose.yml

That will encapsulate and make separation of concern lucid.

**Comment by richiefrost** [comment]
Files moved in [the most recent PR](https://github.com/InitialDLab/AIPro/pull/11)
